### PR TITLE
Add Admin Code 25 : XSS Message As Server (why?)

### PR DESCRIPTION
**Pull request by NonameVM**
Added the ability to send messages from the server name (without username), with XSS.  Accepts 1 string argument : message text
test

### CODE REVIEW

**Comment by NonameVM** [comment]
I don't know how to write code competently yet, I'm just learning ts.

**Comment by NonameVM** [comment]
One problem : raw js scripts don't work

**Comment by NonameVM** [comment]
I forgot to add that "little detail" since I was only doing it for myself

**Comment by elijahr2411** [comment]
That's most likely something to do with your webapp, I'm not sure exactly which webapp version you're using and it appears to be some custom one.

**Comment by elijahr2411** [comment]
All seems good, works fine in testing

**Comment by NonameVM** [comment]
thanks

**Pull request merged**
